#!/usr/bin/env python3
"""
setup_env.py
Cross-platform environment configuration generator for minimal_ros2.
Generates:
  - setup.sh (POSIX bash/zsh for macOS and Linux)
  - setup.bat (Windows Command Prompt)
  - setup.ps1 (Windows PowerShell)
  - SlicerLauncherSettings.ini (Slicer launcher runtime configuration)
"""

import argparse
import glob
import os
import sys
from pathlib import Path

def find_python_packages_dir(install_dir: Path):
    """Find site-packages or dist-packages under install/lib or install/Lib."""
    matches = glob.glob(str(install_dir / "lib" / "python*" / "*packages"))
    if not matches:
        matches = glob.glob(str(install_dir / "Lib" / "*packages"))
    if matches:
        return Path(matches[0])
    return None

def generate_setup_sh(install_dir: Path, output_file: Path):
    py_dir = find_python_packages_dir(install_dir)
    py_rel = f'"{install_dir.resolve()}/{py_dir.relative_to(install_dir)}"' if py_dir else ""

    sh_content = """#!/usr/bin/env sh
# Automatically generated by minimal_ros2 setup_env.py
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

export ROS2_UNDERLAY_DIR="${_DIR}"
export AMENT_PREFIX_PATH="${_DIR}${AMENT_PREFIX_PATH:+:${AMENT_PREFIX_PATH}}"
export PATH="${_DIR}/bin:${PATH}"

if [ "$(uname)" = "Darwin" ]; then
  export DYLD_LIBRARY_PATH="${_DIR}/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
else
  export LD_LIBRARY_PATH="${_DIR}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
fi
"""
    if py_dir:
        rel_path = py_dir.relative_to(install_dir)
        sh_content += f"""
if [ -d "${{_DIR}}/{rel_path}" ]; then
  export PYTHONPATH="${{_DIR}}/{rel_path}${{PYTHONPATH:+:${{PYTHONPATH}}}}"
fi
"""
    output_file.write_text(sh_content, encoding="utf-8")
    output_file.chmod(0o755)

def generate_setup_bat(install_dir: Path, output_file: Path):
    bat_content = """@echo off
rem Automatically generated by minimal_ros2 setup_env.py
set "ROS2_UNDERLAY_DIR=%~dp0"
if "%ROS2_UNDERLAY_DIR:~-1%"=="\\" set "ROS2_UNDERLAY_DIR=%ROS2_UNDERLAY_DIR:~0,-1%"

set "PATH=%ROS2_UNDERLAY_DIR%\\bin;%PATH%"
if defined AMENT_PREFIX_PATH (
  set "AMENT_PREFIX_PATH=%ROS2_UNDERLAY_DIR%;%AMENT_PREFIX_PATH%"
) else (
  set "AMENT_PREFIX_PATH=%ROS2_UNDERLAY_DIR%"
)

if exist "%ROS2_UNDERLAY_DIR%\\Lib\\site-packages" (
  if defined PYTHONPATH (
    set "PYTHONPATH=%ROS2_UNDERLAY_DIR%\\Lib\\site-packages;%PYTHONPATH%"
  ) else (
    set "PYTHONPATH=%ROS2_UNDERLAY_DIR%\\Lib\\site-packages"
  )
)
"""
    output_file.write_text(bat_content, encoding="utf-8")

def generate_setup_ps1(install_dir: Path, output_file: Path):
    ps1_content = """# Automatically generated by minimal_ros2 setup_env.py
$InstallDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$env:ROS2_UNDERLAY_DIR = $InstallDir

$env:PATH = "$InstallDir\\bin;$env:PATH"

if ($env:AMENT_PREFIX_PATH) {
    $env:AMENT_PREFIX_PATH = "$InstallDir;$env:AMENT_PREFIX_PATH"
} else {
    $env:AMENT_PREFIX_PATH = "$InstallDir"
}

$PyDir = "$InstallDir\\Lib\\site-packages"
if (Test-Path $PyDir) {
    if ($env:PYTHONPATH) {
        $env:PYTHONPATH = "$PyDir;$env:PYTHONPATH"
    } else {
        $env:PYTHONPATH = "$PyDir"
    }
}
"""
    output_file.write_text(ps1_content, encoding="utf-8")

def generate_slicer_ini(install_dir: Path, output_file: Path):
    py_dir = find_python_packages_dir(install_dir)
    py_path_str = str(py_dir).replace("\\", "/") if py_dir else ""
    inst_str = str(install_dir.resolve()).replace("\\", "/")

    ini_content = f"""[EnvironmentVariables]
AMENT_PREFIX_PATH={inst_str}
PATH={inst_str}/bin:<DEFAULT>
DYLD_LIBRARY_PATH={inst_str}/lib:<DEFAULT>
LD_LIBRARY_PATH={inst_str}/lib:<DEFAULT>
"""
    if py_path_str:
        ini_content += f"PYTHONPATH={py_path_str}:<DEFAULT>\n"

    output_file.write_text(ini_content, encoding="utf-8")

def main():
    parser = argparse.ArgumentParser(description="Generate environment scripts for minimal_ros2 install directory")
    parser.add_argument("--install-dir", type=Path, default=Path("install"),
                        help="Path to minimal_ros2 install directory")
    args = parser.parse_args()

    install_dir = args.install_dir.resolve()
    if not install_dir.exists():
        print(f"[WARN] Install directory does not exist yet: {install_dir}")
        install_dir.mkdir(parents=True, exist_ok=True)

    sh_file = install_dir / "setup.sh"
    bat_file = install_dir / "setup.bat"
    ps1_file = install_dir / "setup.ps1"
    ini_file = install_dir / "SlicerLauncherSettings.ini"

    generate_setup_sh(install_dir, sh_file)
    generate_setup_bat(install_dir, bat_file)
    generate_setup_ps1(install_dir, ps1_file)
    generate_slicer_ini(install_dir, ini_file)

    print(f"==> Generated environment scripts in {install_dir}:")
    print(f"    - {sh_file.name} (macOS / Linux bash/zsh)")
    print(f"    - {bat_file.name} (Windows cmd)")
    print(f"    - {ps1_file.name} (Windows PowerShell)")
    print(f"    - {ini_file.name} (3D Slicer launcher configuration)")

if __name__ == "__main__":
    main()
